language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.3.1
  - DJANGO_VERSION=1.4
install:
  - pip install -q Django==$DJANGO_VERSION mock https://github.com/rapidsms/rapidsms/zipball/feature/new-routing
  - pip install . --use-mirrors
script: python setup.py test
branches:
  only:
    - master
